services:
  - type: web
    name: uvci-heures
    runtime: image
    repo: https://github.com/Mrkakuzu75/uvci-heures
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://uvci-heures.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: uvcu-mysql-uvci-heures.d.aivencloud.com
      - key: DB_PORT
        value: 13893
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: TON_MOT_DE_PASSE_AIVEN
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
